name: Build And Test the source code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build_and_run_ut
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Instal prerequisites
        run: sudo apt-get install -y build-essential autoconf autoconf-archive automake
      - name: build make_simple_example
        run: cd make_simple_example && make && ./app && make distclean
      - name: build make_example_vars
        run: cd make_example_vars  && make && ./app && make distclean
      - name: build autoconf
        run: cd autoconf && ./prepare_dist.sh && ./src/app && ./clean_up_folder.sh
      